### ISSUE TITLE
Exporting GIF file from AE

### ISSUE THREAD

**Issue by emartin24** [cdaein/mica-gd300#1]
Hi All!

I can't seem to figure out how to create a GIF from After Effects. When I looked it up seems like I need to use media encoder which I am not familiar with. I know I could also import my frames from Illustrator into the Timeline to create the GIF file, what would be the best way to import the different artboards as layers. 

Thanks!

**Comment by calanglais** [comment]
I had to look this up too. In After Effects, with your composition selected/active go to FIle>Export>Add to Adobe Media Encoder Queue. This will launch the media encoder. Once it is open you should see your composition name in the queue list at the top right. To render it as a GIF, scroll through the Preset Browser (bottom left) to Image Sequence. In image sequence there is a folder for GIF. Click and drag the Animated GIF preset to your composition in the queue. Under the preset column in the queue it should say Animated GIF. Select the output destination and click the Green Play Arrow at the Top-Right to start the rendering process.

**Comment by emartin24** [comment]
Thank you so much @calanglais for the awesome suggestion! It worked for me :)
